import { Product, Category, ProductSection } from "@/types/product";

export const categories: Category[] = [
  {
    id: "thoi-trang",
    name: "Thời Trang",
    slug: "thoi-trang",
    icon: "Shirt",
    image: "https://picsum.photos/seed/cat1/200/200",
  },
  {
    id: "dien-thoai",
    name: "Điện Thoại",
    slug: "dien-thoai",
    icon: "Smartphone",
    image: "https://picsum.photos/seed/cat2/200/200",
  },
  {
    id: "thiet-bi-dien-tu",
    name: "Thiết Bị Điện Tử",
    slug: "thiet-bi-dien-tu",
    icon: "Monitor",
    image: "https://picsum.photos/seed/cat3/200/200",
  },
  {
    id: "may-tinh-bang",
    name: "Máy Tính Bảng",
    slug: "may-tinh-bang",
    icon: "Monitor",
    image: "https://picsum.photos/seed/cat4/200/200",
  },
  {
    id: "giay-dep",
    name: "Giày Dép",
    slug: "giay-dep",
    icon: "Trophy",
    image: "https://picsum.photos/seed/cat5/200/200",
  },
  {
    id: "dong-ho",
    name: "Đồng Hồ",
    slug: "dong-ho",
    icon: "Sparkles",
    image: "https://picsum.photos/seed/cat6/200/200",
  },
  {
    id: "may-anh",
    name: "Máy Ảnh",
    slug: "may-anh",
    icon: "Sparkles",
    image: "https://picsum.photos/seed/cat7/200/200",
  },
  {
    id: "laptop",
    name: "Laptop",
    slug: "laptop",
    icon: "Monitor",
    image: "https://picsum.photos/seed/cat8/200/200",
  },
  {
    id: "nuoc-hoa",
    name: "Nước Hoa",
    slug: "nuoc-hoa",
    icon: "Sparkles",
    image: "https://picsum.photos/seed/cat9/200/200",
  },
  {
    id: "phu-kien",
    name: "Phụ Kiện",
    slug: "phu-kien",
    icon: "Sparkles",
    image: "https://picsum.photos/seed/cat10/200/200",
  },
  {
    id: "sach",
    name: "Sách",
    slug: "sach",
    icon: "BookOpen",
    image: "https://picsum.photos/seed/cat11/200/200",
  },
  {
    id: "lam-dep",
    name: "Làm Đẹp",
    slug: "lam-dep",
    icon: "Sparkles",
    image: "https://picsum.photos/seed/cat12/200/200",
  },
  {
    id: "gia-dung",
    name: "Gia Dụng",
    slug: "gia-dung",
    icon: "Home",
    image: "https://picsum.photos/seed/cat13/200/200",
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Áo Thun Basic Cotton",
    slug: "ao-thun-basic-cotton",
    description: "Áo thun chất liệu cotton 100% cao cấp, thoáng mát, thấm hút mồ hôi tốt. Thiết kế đơn giản, dễ phối đồ.",
    price: 199000,
    oldPrice: 299000,
    images: [
      "https://picsum.photos/seed/ao1/400/400",
      "https://picsum.photos/seed/ao2/400/400",
      "https://picsum.photos/seed/ao3/400/400",
    ],
    rating: 4.5,
    soldCount: 1520,
    stock: 200,
    featured: true,
    isFlashSale: false,
    categoryId: "thoi-trang",
    brand: "Local Brand",
    tags: ["bán chạy", "mới"],
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "2",
    name: "Điện Thoại Samsung Galaxy S25",
    slug: "dien-thoai-samsung-galaxy-s25",
    description: "Điện thoại thông minh cao cấp với camera 200MP, chip Exynos 2500, pin 5000mAh.",
    price: 21990000,
    oldPrice: 24990000,
    images: [
      "https://picsum.photos/seed/dt1/400/400",
      "https://picsum.photos/seed/dt2/400/400",
      "https://picsum.photos/seed/dt3/400/400",
    ],
    rating: 4.8,
    soldCount: 890,
    stock: 50,
    featured: true,
    isFlashSale: true,
    categoryId: "dien-thoai",
    brand: "Samsung",
    tags: ["flash-sale", "cao cấp"],
    createdAt: "2026-05-05T00:00:00.000Z",
    updatedAt: "2026-05-05T00:00:00.000Z",
  },
  {
    id: "3",
    name: "Tai Nghe Bluetooth Sony WH-1000XM6",
    slug: "tai-nghe-bluetooth-sony-wh-1000xm6",
    description: "Tai nghe chống ồn chủ động hàng đầu, thời lượng pin 40 giờ, âm thanh Hi-Res.",
    price: 7990000,
    oldPrice: 8990000,
    images: [
      "https://picsum.photos/seed/tn1/400/400",
      "https://picsum.photos/seed/tn2/400/400",
      "https://picsum.photos/seed/tn3/400/400",
    ],
    rating: 4.7,
    soldCount: 2340,
    stock: 120,
    featured: true,
    isFlashSale: false,
    categoryId: "thiet-bi-dien-tu",
    brand: "Sony",
    tags: ["bán chạy", "cao cấp"],
    createdAt: "2026-04-15T00:00:00.000Z",
    updatedAt: "2026-04-15T00:00:00.000Z",
  },
  {
    id: "4",
    name: "Máy Tính Bảng iPad Pro M4",
    slug: "may-tinh-bang-ipad-pro-m4",
    description: "iPad Pro với chip M4, màn hình OLED 12.9 inch, hỗ trợ Apple Pencil Pro.",
    price: 29990000,
    oldPrice: 32990000,
    images: [
      "https://picsum.photos/seed/ip1/400/400",
      "https://picsum.photos/seed/ip2/400/400",
      "https://picsum.photos/seed/ip3/400/400",
    ],
    rating: 4.9,
    soldCount: 560,
    stock: 30,
    featured: true,
    isFlashSale: false,
    categoryId: "may-tinh-bang",
    brand: "Apple",
    tags: ["cao cấp", "mới"],
    createdAt: "2026-05-10T00:00:00.000Z",
    updatedAt: "2026-05-10T00:00:00.000Z",
  },
  {
    id: "5",
    name: "Giày Thể Thao Nike Air Max",
    slug: "giay-the-thao-nike-air-max",
    description: "Giày chạy bộ Nike Air Max với đệm khí, êm ái, phù hợp cho mọi hoạt động thể thao.",
    price: 3500000,
    oldPrice: 4500000,
    images: [
      "https://picsum.photos/seed/gi1/400/400",
      "https://picsum.photos/seed/gi2/400/400",
      "https://picsum.photos/seed/gi3/400/400",
    ],
    rating: 4.6,
    soldCount: 3200,
    stock: 180,
    featured: true,
    isFlashSale: true,
    categoryId: "giay-dep",
    brand: "Nike",
    tags: ["flash-sale", "bán chạy"],
    createdAt: "2026-04-20T00:00:00.000Z",
    updatedAt: "2026-04-20T00:00:00.000Z",
  },
  {
    id: "6",
    name: "Đồng Hồ Thông Minh Apple Watch Ultra 3",
    slug: "dong-ho-thong-minh-apple-watch-ultra-3",
    description: "Apple Watch Ultra 3 với vỏ titan, pin 72 giờ, đo ECG, đo oxy trong máu.",
    price: 18990000,
    oldPrice: 20990000,
    images: [
      "https://picsum.photos/seed/dh1/400/400",
      "https://picsum.photos/seed/dh2/400/400",
      "https://picsum.photos/seed/dh3/400/400",
    ],
    rating: 4.8,
    soldCount: 780,
    stock: 45,
    featured: false,
    isFlashSale: false,
    categoryId: "dong-ho",
    brand: "Apple",
    tags: ["cao cấp", "mới"],
    createdAt: "2026-05-08T00:00:00.000Z",
    updatedAt: "2026-05-08T00:00:00.000Z",
  },
  {
    id: "7",
    name: "Máy Ảnh Sony A7 V",
    slug: "may-anh-sony-a7-v",
    description: "Máy ảnh mirrorless full-frame 61MP, quay video 8K, ổn định hình ảnh 5 trục.",
    price: 45990000,
    oldPrice: 49990000,
    images: [
      "https://picsum.photos/seed/ma1/400/400",
      "https://picsum.photos/seed/ma2/400/400",
      "https://picsum.photos/seed/ma3/400/400",
    ],
    rating: 4.9,
    soldCount: 230,
    stock: 15,
    featured: false,
    isFlashSale: false,
    categoryId: "may-anh",
    brand: "Sony",
    tags: ["cao cấp"],
    createdAt: "2026-05-12T00:00:00.000Z",
    updatedAt: "2026-05-12T00:00:00.000Z",
  },
  {
    id: "8",
    name: "Laptop Dell XPS 16",
    slug: "laptop-dell-xps-16",
    description: "Laptop cao cấp với Intel Core Ultra 9, RAM 32GB, SSD 1TB, màn hình OLED 4K.",
    price: 45990000,
    oldPrice: 49990000,
    images: [
      "https://picsum.photos/seed/lap1/400/400",
      "https://picsum.photos/seed/lap2/400/400",
      "https://picsum.photos/seed/lap3/400/400",
    ],
    rating: 4.7,
    soldCount: 450,
    stock: 25,
    featured: true,
    isFlashSale: false,
    categoryId: "laptop",
    brand: "Dell",
    tags: ["cao cấp"],
    createdAt: "2026-04-10T00:00:00.000Z",
    updatedAt: "2026-04-10T00:00:00.000Z",
  },
  {
    id: "9",
    name: "Nước Hoa Chanel No.5",
    slug: "nuoc-hoa-chanel-no5",
    description: "Nước hoa huyền thoại Chanel No.5, hương thơm nữ tính, sang trọng, lưu hương lâu.",
    price: 4500000,
    oldPrice: 5200000,
    images: [
      "https://picsum.photos/seed/nh1/400/400",
      "https://picsum.photos/seed/nh2/400/400",
      "https://picsum.photos/seed/nh3/400/400",
    ],
    rating: 4.6,
    soldCount: 1200,
    stock: 80,
    featured: false,
    isFlashSale: false,
    categoryId: "nuoc-hoa",
    brand: "Chanel",
    tags: ["cao cấp"],
    createdAt: "2026-03-15T00:00:00.000Z",
    updatedAt: "2026-03-15T00:00:00.000Z",
  },
  {
    id: "10",
    name: "Balo Laptop Thời Trang",
    slug: "balo-laptop-thoi-trang",
    description: "Balo chống sốc cho laptop 15.6 inch, nhiều ngăn, chất liệu vải dù chống thấm.",
    price: 450000,
    oldPrice: 650000,
    images: [
      "https://picsum.photos/seed/bl1/400/400",
      "https://picsum.photos/seed/bl2/400/400",
      "https://picsum.photos/seed/bl3/400/400",
    ],
    rating: 4.4,
    soldCount: 5600,
    stock: 300,
    featured: false,
    isFlashSale: false,
    categoryId: "phu-kien",
    brand: "Local Brand",
    tags: ["bán chạy"],
    createdAt: "2026-02-20T00:00:00.000Z",
    updatedAt: "2026-02-20T00:00:00.000Z",
  },
  {
    id: "11",
    name: "Sách - Đắc Nhân Tâm",
    slug: "sach-dac-nhan-tam",
    description: "Cuốn sách self-help kinh điển nhất mọi thời đại, giúp bạn thành công trong giao tiếp.",
    price: 89000,
    oldPrice: 120000,
    images: [
      "https://picsum.photos/seed/sch1/400/400",
      "https://picsum.photos/seed/sch2/400/400",
      "https://picsum.photos/seed/sch3/400/400",
    ],
    rating: 4.8,
    soldCount: 15000,
    stock: 500,
    featured: false,
    isFlashSale: false,
    categoryId: "sach",
    brand: "First News",
    tags: ["bán chạy"],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "12",
    name: "Kem Chống Nắng Anessa",
    slug: "kem-chong-nang-anessa",
    description: "Kem chống nắng Nhật Bản SPF50+ PA++++, chống nước, không bết dính.",
    price: 350000,
    oldPrice: 420000,
    images: [
      "https://picsum.photos/seed/km1/400/400",
      "https://picsum.photos/seed/km2/400/400",
      "https://picsum.photos/seed/km3/400/400",
    ],
    rating: 4.7,
    soldCount: 8900,
    stock: 250,
    featured: true,
    isFlashSale: true,
    categoryId: "lam-dep",
    brand: "Anessa",
    tags: ["flash-sale", "bán chạy"],
    createdAt: "2026-04-01T00:00:00.000Z",
    updatedAt: "2026-04-01T00:00:00.000Z",
  },
  {
    id: "13",
    name: "Bộ Chăn Ga Gối Cao Cấp",
    slug: "bo-chan-ga-goi-cao-cap",
    description: "Bộ chăn ga gối 4 món chất liệu cotton cao cấp, mềm mại, thoáng mát.",
    price: 1200000,
    oldPrice: 1800000,
    images: [
      "https://picsum.photos/seed/cg1/400/400",
      "https://picsum.photos/seed/cg2/400/400",
      "https://picsum.photos/seed/cg3/400/400",
    ],
    rating: 4.5,
    soldCount: 3400,
    stock: 150,
    featured: false,
    isFlashSale: false,
    categoryId: "gia-dung",
    brand: "Local Brand",
    tags: ["bán chạy"],
    createdAt: "2026-03-20T00:00:00.000Z",
    updatedAt: "2026-03-20T00:00:00.000Z",
  },
  {
    id: "14",
    name: "Robot Hút Bụi Xiaomi S20",
    slug: "robot-hut-bui-xiaomi-s20",
    description: "Robot hút bụi thông minh, lau nhà tự động, điều khiển qua app, bản đồ laser.",
    price: 6990000,
    oldPrice: 8990000,
    images: [
      "https://picsum.photos/seed/rb1/400/400",
      "https://picsum.photos/seed/rb2/400/400",
      "https://picsum.photos/seed/rb3/400/400",
    ],
    rating: 4.6,
    soldCount: 2100,
    stock: 60,
    featured: false,
    isFlashSale: false,
    categoryId: "gia-dung",
    brand: "Xiaomi",
    tags: ["mới"],
    createdAt: "2026-05-11T00:00:00.000Z",
    updatedAt: "2026-05-11T00:00:00.000Z",
  },
  {
    id: "15",
    name: "Áo Khoác Bomber Nam",
    slug: "ao-khoac-bomber-nam",
    description: "Áo khoác bomber phong cách Hàn Quốc, chất liệu dù dày dặn, giữ ấm tốt.",
    price: 550000,
    oldPrice: 750000,
    images: [
      "https://picsum.photos/seed/ak1/400/400",
      "https://picsum.photos/seed/ak2/400/400",
      "https://picsum.photos/seed/ak3/400/400",
    ],
    rating: 4.3,
    soldCount: 4500,
    stock: 200,
    featured: false,
    isFlashSale: false,
    categoryId: "thoi-trang",
    brand: "Local Brand",
    tags: ["bán chạy"],
    createdAt: "2026-02-10T00:00:00.000Z",
    updatedAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "16",
    name: "Loa Bluetooth JBL Flip 7",
    slug: "loa-bluetooth-jbl-flip-7",
    description: "Loa Bluetooth chống nước IP67, pin 20 giờ, âm thanh mạnh mẽ.",
    price: 2990000,
    oldPrice: 3490000,
    images: [
      "https://picsum.photos/seed/lo1/400/400",
      "https://picsum.photos/seed/lo2/400/400",
      "https://picsum.photos/seed/lo3/400/400",
    ],
    rating: 4.5,
    soldCount: 6700,
    stock: 90,
    featured: false,
    isFlashSale: false,
    categoryId: "thiet-bi-dien-tu",
    brand: "JBL",
    tags: ["mới", "bán chạy"],
    createdAt: "2026-05-09T00:00:00.000Z",
    updatedAt: "2026-05-09T00:00:00.000Z",
  },
];

export const productSections: ProductSection[] = [
  {
    id: "section-flash-sale",
    title: "Flash Sale",
    subtitle: "Kết thúc trong",
    type: "flash-sale",
    products: products.filter((p) => p.isFlashSale).slice(0, 8),
    link: "/flash-sale",
  },
  {
    id: "section-trending",
    title: "Xu Hướng Thịnh Hành",
    subtitle: "Sản phẩm được yêu thích nhất",
    type: "trending",
    products: [...products].sort((a, b) => b.soldCount - a.soldCount).slice(0, 12),
    link: "/xu-huong",
  },
  {
    id: "section-recommended",
    title: "Gợi Ý Cho Bạn",
    subtitle: "Dựa trên sở thích của bạn",
    type: "recommended",
    products: products.filter((p) => p.featured).slice(0, 10),
    link: "/goi-y",
  },
  {
    id: "section-best-deals",
    title: "Deal Siêu Hời",
    subtitle: "Giảm giá lên đến 70%",
    type: "best-deals",
    products: products
      .filter((p) => p.oldPrice && (p.oldPrice - p.price) / p.oldPrice >= 0.3)
      .slice(0, 10),
    link: "/deal-sieu-hoi",
  },
];

export const flashSaleEndTime = new Date(
  Date.now() + 23 * 60 * 60 * 1000 + 59 * 60 * 1000 + 59 * 1000
).toISOString();

export const flashSaleProducts = products.filter((p) => p.isFlashSale).slice(0, 8);
export const trendingProducts = [...products].sort((a, b) => b.soldCount - a.soldCount).slice(0, 12);
export const recommendedProducts = products.filter((p) => p.featured).slice(0, 10);
export const bestDealsProducts = products
  .filter((p) => p.oldPrice && (p.oldPrice - p.price) / p.oldPrice >= 0.3)
  .slice(0, 10);
export const electronicsProducts = products
  .filter((p) => ["thiet-bi-dien-tu", "dien-thoai", "may-tinh-bang", "laptop"].includes(p.categoryId))
  .slice(0, 10);
export const fashionProducts = products
  .filter((p) => ["thoi-trang", "giay-dep", "dong-ho"].includes(p.categoryId))
  .slice(0, 10);

export const reviews = [
  {
    id: "rev-1",
    userId: "user-1",
    userName: "Nguyễn Văn A",
    userAvatar: "",
    productId: "1",
    rating: 5,
    comment: "Áo đẹp lắm ạ! Chất vải mềm mịn, mặc rất thoải mái. Giao hàng nhanh, đóng gói cẩn thận. Sẽ ủng hộ shop tiếp.",
    createdAt: "2026-03-15T10:30:00Z",
  },
  {
    id: "rev-2",
    userId: "user-2",
    userName: "Trần Thị B",
    userAvatar: "",
    productId: "1",
    rating: 4,
    comment: "Sản phẩm ok, đúng như mô tả. Chất liệu tốt, form chuẩn. Mình mua size L vừa vặn.",
    createdAt: "2026-03-20T14:20:00Z",
  },
  {
    id: "rev-3",
    userId: "user-3",
    userName: "Lê Văn C",
    userAvatar: "",
    productId: "1",
    rating: 5,
    comment: "Mua lần thứ 2 rồi, chất lượng vẫn rất tốt. Shop nhiệt tình, giao hàng siêu nhanh!",
    createdAt: "2026-04-01T09:15:00Z",
  },
  {
    id: "rev-4",
    userId: "user-4",
    userName: "Phạm Thị D",
    userAvatar: "",
    productId: "2",
    rating: 5,
    comment: "Điện thoại chính hãng, đầy đủ phụ kiện. Máy chạy mượt, camera siêu nét. Rất hài lòng!",
    createdAt: "2026-03-10T11:00:00Z",
  },
  {
    id: "rev-5",
    userId: "user-5",
    userName: "Hoàng Văn E",
    userAvatar: "",
    productId: "2",
    rating: 4,
    comment: "Hàng chính hãng, giá tốt hơn mua ở cửa hàng. Giao hàng hơi chậm nhưng chất lượng sản phẩm tốt.",
    createdAt: "2026-03-25T16:45:00Z",
  },
  {
    id: "rev-6",
    userId: "user-6",
    userName: "Mai Thị F",
    userAvatar: "",
    productId: "3",
    rating: 5,
    comment: "Tai nghe chống ồn cực tốt! Âm thanh trong trẻo, bass mạnh. Đeo thoải mái cả ngày không mỏi tai.",
    createdAt: "2026-02-28T08:30:00Z",
  },
  {
    id: "rev-7",
    userId: "user-7",
    userName: "Đặng Văn G",
    userAvatar: "",
    productId: "4",
    rating: 5,
    comment: "iPad Pro M4 quá xịn! Màn hình đẹp xuất sắc, chạy mượt mọi tác vụ. Đáng đồng tiền!",
    createdAt: "2026-03-05T13:20:00Z",
  },
  {
    id: "rev-8",
    userId: "user-8",
    userName: "Vũ Thị H",
    userAvatar: "",
    productId: "5",
    rating: 4,
    comment: "Giày Nike chính hãng, đẹp như hình. Đi êm chân, phù hợp chạy bộ. Size chuẩn.",
    createdAt: "2026-03-18T10:00:00Z",
  },
  {
    id: "rev-9",
    userId: "user-9",
    userName: "Ngô Văn I",
    userAvatar: "",
    productId: "8",
    rating: 5,
    comment: "Laptop Dell XPS 16 quá mạnh mẽ! Màn hình OLED đẹp không tì vết. Rất đáng mua!",
    createdAt: "2026-03-22T15:30:00Z",
  },
  {
    id: "rev-10",
    userId: "user-10",
    userName: "Lý Thị K",
    userAvatar: "",
    productId: "11",
    rating: 5,
    comment: "Đắc Nhân Tâm - cuốn sách ai cũng nên đọc ít nhất một lần trong đời. Shop giao nhanh, sách đẹp.",
    createdAt: "2026-04-05T09:45:00Z",
  },
  {
    id: "rev-11",
    userId: "user-11",
    userName: "Trương Văn L",
    userAvatar: "",
    productId: "12",
    rating: 5,
    comment: "Kem chống nắng Anessa chính hãng, thấm nhanh không bết dính. Rất hài lòng!",
    createdAt: "2026-03-08T11:30:00Z",
  },
  {
    id: "rev-12",
    userId: "user-12",
    userName: "Đỗ Thị M",
    userAvatar: "",
    productId: "14",
    rating: 4,
    comment: "Robot hút bụi thông minh, dễ sử dụng. Lau nhà sạch. Giao hàng nhanh.",
    createdAt: "2026-03-28T14:00:00Z",
  },
  {
    id: "rev-13",
    userId: "user-13",
    userName: "Bùi Văn N",
    userAvatar: "",
    productId: "16",
    rating: 5,
    comment: "Loa JBL Flip 7 âm thanh mạnh mẽ, bass tốt. Chống nước tốt, mang đi biển thoải mái.",
    createdAt: "2026-03-12T10:15:00Z",
  },
  {
    id: "rev-14",
    userId: "user-14",
    userName: "Hồ Thị O",
    userAvatar: "",
    productId: "9",
    rating: 5,
    comment: "Nước hoa Chanel No.5 chính hãng, mùi thơm quyến rũ, lưu hương lâu. Rất thích!",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "rev-15",
    userId: "user-15",
    userName: "Dương Văn P",
    userAvatar: "",
    productId: "6",
    rating: 5,
    comment: "Apple Watch Ultra 3 chính hãng, pin khỏe, nhiều tính năng. Đeo đẹp và sang!",
    createdAt: "2026-03-30T17:00:00Z",
  },
];